//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gam3iaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donator()
        {
            this.Donation = new HashSet<Donation>();
            this.PhysicalDonation = new HashSet<PhysicalDonation>();
        }
    
        public int ID { get; set; }
        public string DonatorName { get; set; }
        public string DonatorPhone { get; set; }
        public string DonatorAddress { get; set; }
        public string Email { get; set; }
        public string Tag { get; set; }
        public string Notes { get; set; }
        public string Job { get; set; }
        public string DonatorNID { get; set; }
        public Nullable<System.DateTime> JoinedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalDonation> PhysicalDonation { get; set; }
    }
}
