//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gam3iaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralAid
    {
        public int ID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> PoorID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string VolunteerID { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<int> Value { get; set; }
        public string Tag { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Service Service { get; set; }
        public virtual Poor Poor { get; set; }
    }
}
