//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gam3iaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInstallment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> LoanID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> PoorID { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual Poor Poor { get; set; }
    }
}
