//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gam3iaWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gam3iaEntities : DbContext
    {
        public Gam3iaEntities()
            : base("name=Gam3iaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<GmIncome> GmIncome { get; set; }
        public virtual DbSet<GmOutcome> GmOutcome { get; set; }
        public virtual DbSet<OutcomeSource> OutcomeSource { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Relative> Relative { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<LoanInstallment> LoanInstallment { get; set; }
        public virtual DbSet<StudentAid> StudentAid { get; set; }
        public virtual DbSet<Donation> Donation { get; set; }
        public virtual DbSet<PhysicalDonation> PhysicalDonation { get; set; }
        public virtual DbSet<CaseStudy> CaseStudy { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<GeneralAid> GeneralAid { get; set; }
        public virtual DbSet<Loan> Loan { get; set; }
        public virtual DbSet<Volunteer> Volunteer { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Poor> Poor { get; set; }
        public virtual DbSet<Donator> Donator { get; set; }
        public virtual DbSet<Sponsorship> Sponsorship { get; set; }
        public virtual DbSet<SponsorshipResearch> SponsorshipResearch { get; set; }
        public virtual DbSet<Sponsor> Sponsor { get; set; }
        public virtual DbSet<SponsorshipInstallment> SponsorshipInstallment { get; set; }
    }
}
