//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gam3iaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relative
    {
        public int ID { get; set; }
        public string RelativeName { get; set; }
        public string RelativeNID { get; set; }
        public string Relativity { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string EducationStage { get; set; }
        public string EducationOrJob { get; set; }
        public string HealthStatus { get; set; }
    }
}
