//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gam3iaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsorshipInstallment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Amount { get; set; }
        public Nullable<bool> IsCalled { get; set; }
        public string CallerName { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<bool> IsDeliverdToPoor { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> SposorshipID { get; set; }
        public Nullable<bool> January { get; set; }
        public Nullable<bool> February { get; set; }
        public Nullable<bool> March { get; set; }
        public Nullable<bool> April { get; set; }
        public Nullable<bool> May { get; set; }
        public Nullable<bool> June { get; set; }
        public Nullable<bool> July { get; set; }
        public Nullable<bool> August { get; set; }
        public Nullable<bool> September { get; set; }
        public Nullable<bool> October { get; set; }
        public Nullable<bool> November { get; set; }
        public Nullable<bool> December { get; set; }
        public string Year { get; set; }
        public Nullable<int> SponsorID { get; set; }
    
        public virtual Sponsor Sponsor { get; set; }
        public virtual Sponsorship Sponsorship { get; set; }
    }
}
