//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gam3iaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAid
    {
        public int ID { get; set; }
        public string StudyYear { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> RequiredFeesValue { get; set; }
        public Nullable<int> RequiredFeesType { get; set; }
        public Nullable<int> OtherFeesValue { get; set; }
        public Nullable<int> OtherFeesType { get; set; }
        public string VolunteerID { get; set; }
        public Nullable<int> PoorID { get; set; }
        public string SchoolAddress { get; set; }
        public string Notes { get; set; }
        public string StudentName { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Poor Poor { get; set; }
    }
}
